"""Build the same-origin browser catalog from the canonical JSON translations."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from azure_bing_assistant.localization import (
    DEFAULT_UI_LANGUAGE,
    RTL_UI_LANGUAGES,
    SUPPORTED_UI_LANGUAGES,
    frontend_strings,
)


OUTPUT = ROOT / "app" / "frontend" / "locales.js"


def generate_bundle() -> str:
    payload = {
        "defaultLanguage": DEFAULT_UI_LANGUAGE,
        "supportedLanguages": list(SUPPORTED_UI_LANGUAGES),
        "rtlLanguages": list(RTL_UI_LANGUAGES),
        "strings": {
            language: frontend_strings(language)
            for language in SUPPORTED_UI_LANGUAGES
        },
    }
    encoded = json.dumps(payload, ensure_ascii=False, indent=2)
    # Keep the bundle safe even if it is embedded in HTML by a downstream host.
    encoded = (
        encoded.replace("<", "\\u003c")
        .replace(">", "\\u003e")
        .replace("&", "\\u0026")
        .replace("\u2028", "\\u2028")
        .replace("\u2029", "\\u2029")
    )
    return (
        "// Generated by scripts/build_frontend_locales.py; do not edit.\n"
        '"use strict";\n'
        "(function (root, factory) {\n"
        '  if (typeof module === "object" && module.exports) {\n'
        "    module.exports = factory();\n"
        "  } else {\n"
        "    root.CHATBOT_I18N = factory();\n"
        "  }\n"
        "})(globalThis, function () {\n"
        "  function freeze(value) {\n"
        '    if (value && typeof value === "object") {\n'
        "      Object.values(value).forEach(freeze);\n"
        "      Object.freeze(value);\n"
        "    }\n"
        "    return value;\n"
        "  }\n"
        f"  return freeze({encoded});\n"
        "});\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check exact bundle parity without writing.")
    args = parser.parse_args()
    content = generate_bundle().encode("utf-8")
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_bytes() != content:
            print("Frontend locales are missing or stale; run scripts/build_frontend_locales.py.")
            return 1
    else:
        OUTPUT.write_bytes(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
